socialbuilder:
    build:
        context: ./builder-socialmedia
        dockerfile: Dockerfile
    image: builder-socialmedia:1.0.0
    container_name: builder-socialmedia
    mem_limit: 1024m
    mem_reservation: 256m
    env_file:
        - ./builder-socialmedia/.env # 👈 carga el archivo .env del servidor
    environment:
        - NODE_ENV=production
        - PORT=3000
    expose:
        - '3000'
    networks:
        - wi_net
    healthcheck:
        test: ['CMD', 'curl', '-f', 'http://localhost:3000']
        interval: 10s
        timeout: 5s
        retries: 3
